### PR TITLE
Update submitting.md

### PR DESCRIPTION
**Pull request by brianle1301**
Update submitting so that it includes the prettier command

### CODE REVIEW

**Comment by Gr8z** [comment]
You need to include that you need to cd to the addon development folder, and add a notice that if prettier is not found, execute npm install

**Comment by brianle1301** [comment]
No, we run prettier globally @Gr8z. `npm install` has been mentioned somewhere else

**Comment by Gr8z** [comment]
When did you tell the users to install it globally? Prettier was added to the local dependency.

Also, you cannot assume the user has gone through steps in another page.

**Comment by brianle1301** [comment]
No, globally as in for all the addons. Prettier is installed in the addon-development folder, not in each addon folder. These intructions are only applied to the `addon-development` boilerplate, so `npm install` will have to be ran for everything to work @Gr8z

**Comment by Gr8z** [comment]
Yes, I know that prettier is installed on ``addon-development`` directory. That's why I asked you to add the ``cd`` to that folder.

After the command instructions, add an infobox to remind them that this will only work if you are using the official boilerplate.

**Pull request closed without merging**
